### ISSUE TITLE
Setup CI/CD for staging

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore#1]
# story
make sure the app is set up for continuous integration and deployment to staging

# acceptance criteria
- [ ] application setup in CI through to rancher and you can access the staging url
- [ ] parallelize the phases
- [ ] set the .gitlab-ci.yaml up with build/go pattern so the tests and linting errors do not block a deploy if needed urgently
- [ ] able to deploy from branches and from `main`

**Comment by alishaevn** [comment]
https://www.youtube.com/watch?v=hf6Z8OZanec

👆  the tutorial I watched to start off setting up the package for publishing with npm.

**Comment by alishaevn** [comment]
need to place this back on the dev-ops board once https://github.com/scientist-softserv/webstore/issues/4 is complete.

**Comment by alishaevn** [comment]
we do have build and lint actions set up through github actions for the webstore repo. there's also a "deploy" action, but since we switched to vercel to deploy...it isn't in use right now.



![Image](https://user-images.githubusercontent.com/29032869/223182962-2f04e42e-ee52-42b1-9071-fe52405ea479.png)
