### ISSUE TITLE
required request fields

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#106]
# story
the request forms do not validate that any fields have values. we need to add validation.

# acceptance criteria
once we get the `create` code working, we may also find out that the shipping org name is required. in which case we'll need to update the ShippingDetails component to have that input and also make it required

- [ ] description
- [ ] timeline
- [ ] shipping/billing street
- [ ] shipping/billing city
- [ ] shipping/billing country
- [ ] shipping/billing state
- [ ] shipping/billing zip
- [ ] proposals required by

# implementation suggestions
- disable the submit button if all required fields aren't submitted
- use an alert if the submit button was pressed but there are missing required fields
- change the color of the missing required fields

**Comment by summer-cook** [comment]
Notes:

There are 2 ways to add validations: 
- browser defaults
- custom bootstrap validations

This is what the browser defaults look like (cannot be styled at all with css)


![Image](https://user-images.githubusercontent.com/73361970/210582959-a5751e12-668a-4c20-8825-5b5fa46af755.png)



This is what the bootstrap validations look like (they can also be styled with css however we want)


![Image](https://user-images.githubusercontent.com/73361970/210583058-25460775-ffda-488d-a92a-af91c2e7a889.png)


Since the webstore doesn't have react bootstrap, the custom validations do not work. For bootstrap's javascript to work in a react app, the app must have react bootstrap. I think this is actually a good enough reason to add it, especially since now having react bootstrap js available in the webstore would have made several other tickets easier. Personally i think the UI for the custom validations looks way better vs. the browser defaults. It might be possible to add only the form component/javascript for now which would bring in the validations and make this usable across future forms... I will look into it.

**Comment by summer-cook** [comment]
After investigating the browser default validation more thinking that would be the simplest option, unfortunately the HTML5 Default Validation doesn't just work in React/only works in some cases:

https://share.getcloudapp.com/OAu2G5Ll

I followed all the steps here to see why it wasn't working: https://fellowtuts.com/html-css/html5-required-attribute-validation-not-working/ but it still is not consistent.

i was also looking into how to set up the validations themselves and found the libraries [formik](https://formik.org/docs/guides/validation) & [yup](https://www.npmjs.com/package/yup) which are used together to simplify forms. I'm going to try adding those because I think it will save a lot of time

**Comment by summer-cook** [comment]
nvm, got it!! 

![Image](https://user-images.githubusercontent.com/73361970/210642350-f3e4e45f-854e-46e3-95e0-eb7567523531.png)

**Comment by summer-cook** [comment]
Jk, I didn't. I tried to just pull over the JS only from bootstrap, but the behavior of the form is still off. There may be a way to fix it if we want to keep trying to go this route and avoid adding react-bootstrap. Here is the code in the handeSubmit in that version that explains the behavior

```
  const handleSubmit = (event) => {
    event.preventDefault()
    // Bootstrap validation starts here
    // Currently this is the behavior:
    // If i fill out the form correctly, the values are submitted
    // If i fill out the form incorrectly (missing fields etc),
    //  the values are not submitted, but the validations DO show up.
    // After fixing an incorrect form, if I try to submit again, the values are NOT submitted.
    // since this method uses regular bootstrap JS vs react bootstrap, i think that there is an issue with the state of the form. react bootstrap includes a 'validated' prop and i think using that would work better here. 
    var forms = document.querySelectorAll('.needs-validation')
    // Loop over them and prevent submission
    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
          form.classList.remove('needs-validation')
          console.log(form.classList)
        }, false)
      })
    // end Bootstrap validation
    if (requestForm.billingSameAsShipping === true) {
      Object.assign(requestForm.billing, requestForm.shipping)
    }

    // TODO(alishaevn): comment this back in when it's working
    // createRequest(requestForm)
    console.log(requestForm)
  }
```

I'm going to go ahead and add react-bootstrap, since I feel like at this point it is the best option & it's already set up to handle this.
