### ISSUE TITLE
SPIKE: research getDerivedStateFromProps

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#118]
# story
_this is a non customer facing issue_

when loading the new request page, the console error below appears. we should look into whether we want to update our code per the [mentioned docs](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html).

# demo

![Image](https://user-images.githubusercontent.com/29032869/212174129-b6bf4d54-ed41-44b8-bda8-20360c345d9a.png)

**Comment by summer-cook** [comment]
The docs basically say that the lifecycle method `componentWillReceiveProps` is now being automatically renamed to `UNSAFEcomponentWillRecieveProps` and it should be replaced or potentially use the `getDerivedStateFromProps` instead

Good explanation of what is happening here: https://stackoverflow.com/a/68705560/15106020

This warning is an error coming from a dependency, vs. from our code (I searched all of webstore & component lib for `componentWillReceiveProps`), so I don't think there is much we can do about it unless we fork whatever dependency it is or wait for them to fix it in a newer release. Although, looking at the stack trace (ours look slightly different) it is kind of hard to tell which dependency.. unless its NextJS itself?

[Image](https://user-images.githubusercontent.com/73361970/214618374-eab98c5a-b2ca-4bf3-929c-1593df69d4f2.png)

I did also find that nextJS is [set to strict mode](https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode), so whichever dependency that is causing this must not be.

**Comment by summer-cook** [comment]
I'm looking at the stack trace again, and I see at the bottom it says update the following component: Form

our <Form> is coming from react json schema form, which I remember Steven saying has not been updated in a while, so that makes sense. i also looked at their repo and they did have a previously opened issue for this warning https://github.com/rjsf-team/react-jsonschema-form/pull/2010 but it has since been closed
the fix that the guy proposed seemed pretty complicated. But i commented on it just in case to ask if they plan on fixing it
