### ISSUE TITLE
Hide featured service page / make optional

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#131]
# Summary
By default, the featured services title should link to a request form for that service, rather than a separate service page

# Implementation suggestion
Since the service page already exists, we can make a boolean that sets whether service page is true or false (false by default). if true, the title will still link to the service page. if false, it will link to the request form

# Acceptance Criteria
- [ ] As a user, I can see that the featured services link to their respective request forms by default
- [ ] As a user, I can change an option to enable the featured service page if I want to use it.

**Comment by alishaevn** [comment]
re: implementation

the ItemGroup component already accounts for a link being sent to it. currently, the link we pass is for the featured service page. so instead of adding another conditional, we could just change the path that we're passing. 

the `configureServices` function may need to be adjusted, or a new function created altogether. the ItemGroup component could pretty much be left alone though.
