### ISSUE TITLE
refactor the api for dynamic form data

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#162]
# Story
The [dynamic form serializer](https://github.com/assaydepot/scientist_api_v2/blob/main/lib/scientist_api_v2/app/serializers/scientist_api_v2/dynamic_form_serializer.rb) that creates the information we need to feed into the react json schema forms (rjsf) does not work with rsjf v5. Currently, we are doing the proper formatting in the webstore with the [dynamicFormSchema](https://github.com/scientist-softserv/webstore/blob/main/utils/api/requests.js#L168) and [dynamicFormUiSchema](https://github.com/scientist-softserv/webstore/blob/main/utils/api/requests.js#L223) functions. Instead, we would like to refactor the code in the api to return us the proper format.

We can refactor this code instead of adding additional code because it isn't currently being used in any other application.

# Acceptance criteria
- [ ] we are able to receive an rsjf v5 formatted schema value from the api
- [ ] we are able to receive an rsjf v5 formatted ui options value from the api

# Implementation suggestions
- Clone `rx` locally and get it running
- Clone `scientist_api_v2` and get it running
- Have the webstore running locally and point it at the local instance of `rx`
- Refactor the `create_react_properties` method and possibly `convert_to_react` too

**Comment by summer-cook** [comment]
## notes

- started on this ticket but I am blocked because I am waiting for AWS credentials/access to the dev vault from someone on the product team
- rx must be running to get api_v2 running
- for installation instructions for api_v2, refer to api_v1

**Comment by summer-cook** [comment]
Notes from spike:

General api helpful info
- we got rx running & pointing to a local version of the api
- rx does not actually use the api, but the api is installed as an engine in the rx app
- the api cannot be run independently of rx


- discovered that the `create_react_app` and `convert_to_react` methods are not actually being called before sending the dynamic form json to the webstore via the initialize endpoint.
- its possible that the api should either remove or otherwise note that the `create_react_app` and `convert_to_react`  methods are not being used/only being used by rxlite which is out of commission.
- paired with Ron and the conclusion was that the api should not necessarily know about its clients, therefore the dynamicFormSchema and dynamicFormUIschema methods should remain in the webstore vs. being moved to api, therefore this ticket should be closed.
